<<<<<<< HEAD
# Default values for Paperless.

image:
  repository: thepaperlessproject/paperless
  pullPolicy: IfNotPresent
  tag: latest

args: "['gunicorn', '-b', '0.0.0.0:8000']"

strategy:
  type: Recreate

# See the following files for supported environment variables
# https://github.com/the-paperless-project/paperless/blob/master/docker-compose.env.example
# https://github.com/the-paperless-project/paperless/blob/master/paperless.conf.example
env:
  # TZ: Europe/London
  PAPERLESS_OCR_LANGUAGES: eng
  # PAPERLESS_FORGIVING_OCR: true
  # PAPERLESS_DISABLE_LOGIN: true
  # PAPERLESS_INLINE_DOC: true
  # PAPERLESS_OCR_THREADS:
  # PAPERLESS_CONVERT_DENSITY:

service:
  port:
    port: 8000

persistence:
  data:
    enabled: false
    mountPath: /usr/src/paperless/data
  media:
    enabled: false
    mountPath: /usr/src/paperless/media
  consume:
    enabled: false
    mountPath: /consume
  export:
    enabled: false
    mountPath: /export

additionalContainers:
  - name: consumer
    image: thepaperlessproject/paperless:latest
    imagePullPolicy: IfNotPresent
    args: ['document_consumer']
    volumeMounts:
    - mountPath: /usr/src/paperless/data
      name: data
    - mountPath: /usr/src/paperless/media
      name: media
    - mountPath: /consume
      name: consume
    - mountPath: /export
      name: export
=======
#
# IMPORTANT NOTE
#
# This chart inherits from our common library chart. You can check the default values/options here:
# https://github.com/k8s-at-home/charts/tree/master/charts/common/values.yaml
#

image:
  repository: jonaswinkler/paperless-ng
  pullPolicy: IfNotPresent
  tag: latest

strategy:
  type: Recreate

# See the following files for additional environment variables
# https://github.com/jonaswinkler/paperless-ng/tree/master/docker/compose/
# https://github.com/jonaswinkler/paperless-ng/blob/master/paperless.conf.example
env:
  COMPOSE_PROJECT_NAME: paperless
  PAPERLESS_REDIS: redis://localhost:6379
  PAPERLESS_OCR_LANGUAGE: eng
  # USERMAP_UID: 1000
  # USERMAP_GID: 1000
  # PAPERLESS_TIME_ZONE: Europe/London

service:
  port:
    port: 8000

ingress:
  enabled: false

persistence:
  data:
    enabled: false
    mountPath: /usr/src/paperless/data
    emptyDir: false
  media:
    enabled: false
    mountPath: /usr/src/paperless/media
    emptyDir: false
  consume:
    enabled: false
    mountPath: /usr/src/paperless/consume
    emptyDir: false
  export:
    enabled: false
    mountPath: /usr/src/paperless/export
    emptyDir: false

additionalContainers:
  - name: broker
    image: redis:6.0
    imagePullPolicy: IfNotPresent
>>>>>>> upstream/master
