# Default values for dizqueTV.

image:
  repository: vexorian/dizquetv
  pullPolicy: IfNotPresent
  tag: 1.3.0

strategy:
  type: Recreate

service:
  port:
    port: 8000

env: {}
  # TZ: UTC
  # PUID: 1001
  # PGID: 1001

persistence:
  config:
    enabled: false
    emptyDir: false
    mountPath: /home/node/app/.dizquetv
